### ISSUE TITLE
Needs some more work to distribute 

### ISSUE THREAD

**Issue by garymcintire** [haarnoja/softqlearning#2]
I had to do the following things to get this to work for me and I think most people will as well. Maybe you could add these changes to it

cloned latest rllab and copied mujoco_py to the softqlearning/rllab dir
cp -rp  rllab/rllab/mujoco_py ~/clones/softqlearning/rllab/
mkdir /home/gary/clones/softqlearning/vendor/mujoco
cp /home/gary/mjpro131/bin/libmujoco131.so /home/gary/clones/softqlearning/vendor/mujoco
cp /home/gary/mjpro131/bin/libglfw.so.3 /home/gary/clones/softqlearning/vendor/mujoco
cp /home/gary/mjpro131/bin/mjkey.txt  /home/gary/clones/softqlearning/rllab/mujoco_py/../../vendor/mujoco

Added the following to rllab/config.py
TF_GPU_ALLOW_GROWTH = True
TF_GPU_MEM_FRAC = .1
TF_LOG_DEVICE_PLACEMENT = False
TF_USE_GPU = True

**Comment by haarnoja** [comment]
I have now incorporated these modifications. Thanks!
