### ISSUE TITLE
Can we have some more examples the are in the blog?

### ISSUE THREAD

**Issue by garymcintire** [haarnoja/softqlearning#3]
The blog has more experiments than there are in this distribution. ant, compositionality, etc
http://bair.berkeley.edu/blog/2017/10/06/soft-q-learning/

Could we get that code as well?

Thanks for such a great paper and code!!!

**Comment by haarnoja** [comment]
Thanks for the interest! Some of the work we presented in the blog is part of unpublished research (e.g. compositionality stuff), so that's why they are not included in this repo. I'm planning to include more examples in the future.
