### ISSUE TITLE
Temperature parameter is not handled properly

### ISSUE THREAD

**Issue by haarnoja** [haarnoja/softqlearning#5]
The temperature parameter (alpha) is missing from the TD updates. For example
https://github.com/haarnoja/softqlearning/blob/aca29d2aee66c44ee052a298f049a22fa14792a5/softqlearning/algos/softqlearning.py#L353 should have alpha as in Eq. (10) in the [paper](https://arxiv.org/pdf/1702.08165.pdf). The code is correct only if alpha = 1.

As a quick fix to change the temperature, you can set scale_reward = 1 / temperature and alpha=1, which has an equivalent effect as discussed on [page 2](https://arxiv.org/pdf/1702.08165.pdf).

**Comment by haarnoja** [comment]
Latest [refactor](https://github.com/haarnoja/softqlearning/pull/6) removes the temperature coefficient (`alpha`). To adjust the temperature, you can change `reward_scale` instead.

**Comment by haarnoja** [comment]
In my experience, annealing alpha to zero was little problematic because of how it enters the value function (V = alpha * log sum exp (Q / alpha)) and naive way of implementing this and setting alpha -> 0 obviously fails. How did you fix this? If you'd like to share your code, I'd be happy to merge your PR :).

**Comment by immars** [comment]
that's right, in my experiment, if alpha is annealed below a threshold (near 0.08 or so), the training becomes numerically unstable. But it could take a much larger value at the beginning of the training to encourage exploration.

the code is now in a private branch of [hobotrl](https://github.com/hobotrl/hobotrl). the code structure is very different from this repo i think, and is hard to merge. I created a [gist](https://gist.github.com/immars/7d22e32104528199ab56ef48f957c8a3) with relevant code pieces.
`alpha_exploration` could be a object of a subclass of python `float`, with variable values when evaluated each time as `float`.

**Comment by immars** [comment]
I've pushed to [hobotrl](https://github.com/hobotrl/hobotrl) for your reference.
